name: Kotlin CI with Gradle

on:
  push:
    branches:
      [main, CI]
  pull_request:
    branches:
      [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
            distribution: "oracle"
            java-version: 21

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Testing
        run: ./gradlew test

      - name: Test covering 
        run: ./gradlew jacocoTestReport
